2017/06/17 08:14:16The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1282
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1221
2017/06/17 08:16:38The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:16:38The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:16:42The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:16:43The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:17:02The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:17:02The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:17:19The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:17:30The service translate has thrown an exception: Google.GoogleApiException: Parameter validation failed for "q"
   場所 Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   場所 Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteUnparsedAsync>d__30.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__27.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__26.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<TranslateTextAsync>d__94.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1283
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   場所 Kikisen_VC_WPF.MainWindow.<FuncTranslateTextToSpeech>d__91.MoveNext() 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 1222
2017/06/17 08:20:24System.ArgumentOutOfRangeException: startIndex に文字列の長さより大きい値を指定することはできません。
パラメーター名:startIndex
   場所 System.String.Substring(Int32 startIndex, Int32 length)
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_3.<Worker_DoWork_GCS_Recog>b__2(Boolean bContainAlpha) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 841
2017/06/17 08:25:29System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:29System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:30System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:31System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:32System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:33System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:33System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:33System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:33System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:25:33System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:33:56System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:34:06System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

2017/06/17 08:34:09System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Kikisen_VC_WPF.MainWindow.<>c__DisplayClass88_1.<Worker_DoWork_GCS_Recog>b__7(Object sender2, RecordDataAvailabledEventArgs e2) 場所 C:\Users\rozen\documents\visual studio 2017\Projects\Kikisen-VC-WPF\Kikisen-VC-WPF\MainWindow.xaml.cs:行 978
---> (内部例外 #0) System.Threading.Tasks.TaskCanceledException: タスクが取り消されました。<---

